### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by bytestream** [supportpal/pollcast#7]
After several hours of leaving a tab open I'm noticing the `/messages` route starts returning 404 Not Found, I'm assuming from  https://github.com/supportpal/pollcast/blob/42276d8cc5a3d07ed0ab3026c46e1d55e91d341b/src/Http/Controller/SubscriptionController.php#L35 as the responses say member not found.

I think this happens if the tab becomes inactive. I noticed that the request time was about 2 minutes after the prior request. In modern browsers the inactive tab thread not given priority so it stops running the AJAX so often (ref: https://discourse.mozilla.org/t/replace-settimeout-setinterval-with-alarms/74336/5). Garbage collection removes the user if they don't check in for 60 seconds.

Not necessarily a bug but if the user is removed, then they need to refresh the page to rejoin when the tab is active again or we need some way to rejoin without refreshing the page.

Alternative is to increase the garbage collection timeout

**Comment by jshah4517** [comment]
Suggest triggering a call to the subscribe endpoint automatically when this happens, an easy way to re-connect if it has been garbage collected due to what you mentioned.
